set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'

#Status bar Option
set -g allow-rename off
# set -g status-position top
set -g status-interval 5

set -g status-left ""
set -g status-right "#{?client_prefix,#[bg=colour136],#[bg=colour166]}#[fg=colour0] #S "


# Set the prefix to Ctrl+a
set -g prefix C-a

# Remove the old prefix
unbind C-b

# Send Ctrl+a to applications by pressing it twice
bind C-a send-prefix

# Turn the mouse on
set -g mouse

set -ag terminal-overrides ",xterm-255color:RGB"

set -g pane-border-style 'fg=colour136'
set -g pane-active-border-style 'fg=colour166'

# messages
set -g message-style 'fg=colour2 bg=colour0 bold'
set -g status-style bg=default

run '~/.tmux/plugins/tpm/tpm'

