export ZSH="$HOME/.oh-my-zsh"
export PATH="$HOME/.local/bin:$PATH"

export GOPATH="$HOME/Workspace/go"
#Change escape key on zsh vim mode to jk
export ZVM_VI_INSERT_ESCAPE_BINDKEY=jk
ZSH_THEME="robbyrussell"

plugins=(
    git
    dnf
    zsh-syntax-highlighting
    zsh-autosuggestions
    zsh-vi-mode
)

#STARTUPS SCRIPTS
source $ZSH/oh-my-zsh.sh

alias tn='tmux new-session -s $(basename $PWD)'
alias ta='tmux a'
alias goto='DIR=$(zoxide query -l | fzf --reverse --print0) ; cd $DIR'
alias vi='nvim'
alias vim='nvim'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

eval "$(starship init zsh)"

eval "$(zoxide init zsh)"

zvm_after_init_commands+=('[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh')

